FROM node:alpine as development

WORKDIR /usr/src/app

COPY package.json .

COPY package-lock.json .

RUN npm install  --force 

COPY . .

RUN npm run build 

FROM node:alpine as production 

WORKDIR /usr/src/app

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

COPY package.json .

COPY package-lock.json .

RUN npm install --prod --force

COPY --from=development /usr/src/app/dist ./dist

CMD [ "node","dist/auth/main" ]

